
# if [ $TERM_PROGRAM == "vscode" ]; then
#   echo "Sorry you are in vscode"
# elif command -v tmux &> /dev/null && [ -z "$TMUX" ]; then
#   tmux attach -t default || tmux new -s default
# fi

#generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc
