model: ollama:llama3.2
highlight: true

clients:
  - type: openai
    api_key: <omitted>

  - type: openai-compatible
    name: ollama
    api_base: http://localhost:11434/v1
    models:
      - name: qwen2.5-code
        max_input_tokens: 2048
      - name: llama3.2
        max_input_tokens: 2048
      - name: mistral
        max_input_tokens: 2048

  - type: claude
    api_key: <omitted>
