model: ollama:llama3.1
highlight: true

clients:
  - type: openai
    api_key: <omitted>

  - type: ollama
    api_base: http://localhost:11434
    models:
      - name: qwen2
        max_input_tokens: 2048
      - name: llama3.1
        max_input_tokens: 2048
      - name: gemma2
        max_input_tokens: 2048

  - type: claude
    api_key: <omitted>
