name: local-ai

services:
  ollama:
    container_name: ollama
    pull_policy: always
    build:
      context: ./ollama
    restart: on-failure:3
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    healthcheck:
      test: ["CMD", "curl", "localhost:11434"]
      start_period: 30s
      interval: 1m
      timeout: 7s
      retries: 3
    environment:
      - OLLAMA_NUM_PARALLEL=3
      - OLLAMA_KEEP_ALIVE="10m"
  open-webui:
    container_name: open-webui
    depends_on:
      open-webui-mcpo:
        condition: service_started
        required: true
      ollama:
        condition: service_healthy
        required: false
    image: ghcr.io/open-webui/open-webui:cuda
    restart: on-failure:3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3088:8080"
    volumes:
      - open-webui:/app/backend/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
  open-webui-mcpo:
    container_name: open-webui-mcpo
    pull_policy: always
    build:
      context: ./mcpo
    restart: on-failure:3
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  ollama:
    name: "ollama-data"
  open-webui:
    name: "open-webui-data"
