name: local-ai

services:
  ollama:
    container_name: ollama
    pull_policy: always
    build:
      context: ./ollama
    restart: on-failure:3
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    healthcheck:
      test: ["CMD", "curl", "localhost:11434"]
      start_period: 30s
      interval: 1m
      timeout: 7s
      retries: 3
    environment:
      - OLLAMA_NUM_PARALLEL=3
      - OLLAMA_KEEP_ALIVE="10m"

  open-webui:
    container_name: open-webui
    depends_on:
      #  open-webui-pipelines:
      #  condition: service_started
      ollama:
        condition: service_healthy
        required: false
    image: ghcr.io/open-webui/open-webui:cuda
    restart: on-failure:3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3088:8080"
    volumes:
      - open-webui:/app/backend/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia

  #open-webui-pipelines:
    #  container_name: open-webui-pipelines
    #image: ghcr.io/open-webui/pipelines:main
    #restart: on-failure:3
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    #ports:
    #  - "9099:9099"
    #volumes:
    #  - pipelines:/app/pipelines
    #environment:
    #  - PIPELINES_URLS="https://raw.githubusercontent.com/open-webui/pipelines/main/examples/pipelines/rag/haystack_pipeline.py;https://raw.githubusercontent.com/open-webui/pipelines/main/examples/pipelines/integrations/wikipedia_pipeline.py;https://raw.githubusercontent.com/open-webui/pipelines/main/examples/pipelines/providers/anthropic_manifold_pipeline.py;https://raw.githubusercontent.com/open-webui/pipelines/main/examples/pipelines/providers/openai_dalle_manifold_pipeline.py"
    #runtime: nvidia

volumes:
  ollama:
    name: "ollama-data"
  open-webui:
    name: "open-webui-data"
  #pipelines:
    #  name: "pipelines-data"
