# Use the existing ollama image as the base image (https://hub.docker.com/r/ollama/ollama)
FROM ollama/ollama

# Add your environment variables
ENV OLLAMA_MAX_LOADED_MODELS=3

# You can also add other configuration or setup commands here if needed
