#!/usr/bin/env bash

# Ask for confirmation using zenity
cdialog() {
    zenity --question --title="Confirm" --text="Are you sure you want to $1?" --width=200
    return $?
}

# Notify function with optional sleep time parameter
notify() {
    local message=$1
    local delay=${2:-2} # Default to 2 seconds if not provided
    notify-send --expire-time=1200 --icon="system-shutdown-symbolic" "System Info" "$message"
    sleep $delay # Using the provided sleep time or default
}

cdialog "$1"

if [[ "$?" == 0 ]]; then
    playerctl --all-players stop
    sleep 0.25s
    case "$1" in
    'shutdown')
        notify "Shutting down in 2 seconds..." 2
        systemctl poweroff
        ;;
    'reboot')
        notify "Rebooting in 2 seconds..." 2
        systemctl reboot
        ;;
    'hibernate')
        notify-send --expire-time=4000 --icon="system-shutdown-symbolic" "System Info" "Error! System doesn't support hibernation"
        ;;
    'lock')
        notify "Locking..." 0.5
        swaylock
        ;;
    'suspend')
        notify "Suspending..." 0.5
        swaylock
        sleep 0.5s
        systemctl suspend
        ;;
    'logout')
        notify "Logging out of Hyprland..." 0.5
        hyprctl dispatch exit none
        ;;
    *)
        notify-send --expire-time=4000 --icon="arch-error-symbolic" "Error" "Uknown system command"
        exit 1
        ;;
    esac
else
    exit
fi
