/**
 * A Theme is a set of options that will be applied
 * ontop of the default values. see options.js for possible options
 */
import { Theme, WP, lightColors } from './settings/theme.js';

export default [
  Theme({
    name: "Catppuccin Mocah",
    "color.red": "#f38ba8",
    "color.green": "#a6e3a1",
    "color.yellow": "#f9e2af",
    "color.blue": "#89b4fa",
    "color.magenta": "#cba6f7",
    "color.teal": "#94e2d5",
    "color.orange": "#fab387",
    "theme.bg": "#1e1e2e",
    "theme.fg": "lighten(#CDD6F4, 10%)",
    "desktop.screen_corners": false,
    "bar.separators": false,
    "bar.style": "separated",
    "accent.accent": "#45475a",
    "accent.fg": "#181825",
    "border.width": 0,
    "desktop.shadow": "rgba(17, 17, 27, 0.8)",
    "accent.gradient":
      "to right, #b4befe, lighten(mix($magenta, $blue, 70%), 18%)",
    "font.font": "SF Pro Rounded Regular",
    "font.mono": "SF Mono SemiBold",
    "font.size": 14,
    "hypr.inactive_border": "#6C7086",
    "hypr.active_border": "#b4befe",
    "desktop.drop_shadow": false,
    "widget.bg": "$accent",
    "widget.opacity": 64,
  }),
  Theme({
    name: "Kitty Dark",
    icon: "󰄛",
    "desktop.wallpaper.img": WP + "kittybl.jpeg",
  }),
  Theme({
    name: "Kitty Light",
    icon: "󰄛",
    "desktop.wallpaper.img": WP + "kitty.jpeg",
    ...lightColors,
    "theme.widget.bg": "$accent",
    "theme.widget.opacity": 64,
  }),
  Theme({
    name: "Leaves",
    icon: "󰌪",
    "desktop.wallpaper.img": WP + "leaves.jpg",
    "theme.accent.accent": "$green",
    "theme.accent.gradient": "to right, $accent, darken($accent, 14%)",
    "theme.widget.opacity": 92,
    "border.opacity": 86,
    "theme.bg": "transparentize(#171717, 0.3)",
    "bar.style": "floating",
    radii: 0,
  }),
  Theme({
    name: "Ivory",
    icon: "󰟆",
    ...lightColors,
    "desktop.wallpaper.img": WP + "ivory.png",
    "desktop.wallpaper.fg": "$bg_color",
    "desktop.screen_corners": false,
    "bar.separators": false,
    "bar.style": "separated",
    "theme.widget.bg": "$accent",
    "theme.widget.opacity": 64,
    "desktop.drop_shadow": false,
    "border.width": 2,
    "border.opacity": 0,
    "theme.accent.gradient": "to right, $accent, darken($accent, 6%)",
    "hypr.inactive_border": "rgba(111111FF)",
  }),
  Theme({
    name: "Space",
    icon: "",
    "desktop.wallpaper.img": WP + "space.jpg",
    spacing: 11,
    padding: 10,
    radii: 12,
    "theme.accent.accent": "$magenta",
    "desktop.screen_corners": false,
    "desktop.clock.enable": false,
    "bar.separators": false,
    "bar.icon": "",
    "theme.bg": "transparentize(#171717, 0.3)",
    "theme.widget.opacity": 95,
    "bar.flat_buttons": false,
  }),
];
