#!/bin/sh

# To allow some programs not in (/usr/bin) to be run during Hyprland initialization
export PATH=$HOME/.local/bin:$PATH

. /etc/profile

if [ -f "$HOME/.shell-env" ]; then
  . "$HOME/.shell-env"
fi

exec Hyprland
