#!/usr/bin/env bash

# Ask for confirmation
cdialog () {
    yad --title='Confirm?' --css="box { padding: 0.5rem; }" --center --fixed --undecorated --button=Yes:0 --button=No:1 --text="You sure you wanna $1?" --text-align=center --align=center --justify=center --buttons-layout=spread
}

notify () {
    notify-send --expire-time=1200 --icon="system-shutdown-symbolic" "System Info" "$1"
}

cdialog "$1"

if [[ "$?" == 0 ]]; then
    playerctl --all-players stop
    sleep 0.25s
    if [[ "$1" == 'shutdown' ]]; then
        notify "Shutting down..."
        sleep 0.25s
        systemctl poweroff
    elif [[ "$1" == 'reboot' ]]; then
        notify "Rebooting..."
        sleep 0.25s
        systemctl reboot
    elif [[ "$1" == 'hibernate' ]]; then
        notify-send --expire-time=4000 --icon="system-shutdown-symbolic" "System Info" "Error! System doesn't support hibernation"
    elif [[ "$1" == 'lock' ]]; then
        notify "Locking..."
        sleep 0.25s
        swaylock
    elif [[ "$1" == 'suspend' ]]; then
        notify "Suspending..."
        swaylock
        sleep 0.5s
        systemctl suspend
    elif [[ "$1" == 'logout' ]]; then
        notify "Logging out of Hyprland..."
        sleep 0.25s
        hyprctl dispatch exit none;
        logout
    fi
else
    exit
fi
