# Spaceship theme config variables

SPACESHIP_CHAR_SYMBOL_ROOT=">>"
SPACESHIP_USER_SHOW="needed"
SPACESHIP_VENV_SYMBOL="🐍 "
SPACESHIP_TIME_SHOW="true"
SPACESHIP_EXIT_CODE_PREFIX=""
SPACESHIP_TIME_FORMAT="%T"
SPACESHIP_TIME_COLOR="white dimmed"
SPACESHIP_EXIT_CODE_SHOW="true"
